# Generated by Django 5.2 on 2025-05-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
